### ISSUE TITLE
感觉cookies很容易失效

### ISSUE THREAD

**Issue by pc10201** [leongpeng/Alipay#5]
感觉cookies很容易失效，我用python写了这个程序
大概有效期不到十分钟

**Comment by albertofwb** [comment]
一楼遇到的问题我也遇到过，貌似alipay的cookie有时效性限制，我的这个cookie貌似也就坚持了10+分钟

**Comment by leongpeng** [comment]
在哪台机器上获取的 cookie 就要在哪台机器上跑.
